### ISSUE TITLE
Printing possibilities?

### ISSUE THREAD

**Issue by slongberry** [justinmanley/Leaflet.Illustrate#16]
I really like the way that Leaflet.Illustrate looks and functions but I really need to get the text boxes to print through Geoserver/Mapfish print server. Right now, I can get the text to print, but not the box behind the text. This is due to the fact that the entire annotation is seen as a marker and leaflet.print is treating it as an icon with a label. I know, none of this is Leaflet.Illustrate's concern.

What I am wondering is if there is some way to leave the rectangle behind the text as a L.Rectangle rather than using HTML to format the box? This would allow me to pass the rectangle to the print service as one object that it knows how to handle and then the text as it is now.

Thanks for any thoughts on this.

Scott

**Comment by justinmanley** [comment]
Hmmmm.

I'm not sure what the best way to handle this is, since I've never used `L.print`. One possible solution would be to actually create an `L.Rectangle` behind the textbox with exactly the same dimensions when you need to print a textbox.

You can get the dimensions of the textbox by calling [`L.Illustrate.Textbox#getSize`](https://github.com/justinmanley/Leaflet.Illustrate/blob/master/src/core/L.Illustrate.Textbox.js#L77).
